### ISSUE TITLE
Headers not Defined

### ISSUE THREAD

**Issue by ghost** [shukrant25/scrape-all-pages-from-any-site#1]
Fix: 

# Get all the URLs from Sitemap
from bs4 import BeautifulSoup
from requests import get
import re
import csv

def ScrapPage(urlMain):
    response = get(urlMain,headers=headers)
    content = BeautifulSoup(response.content, "lxml")
    urls = content.find_all("loc")
    index = 0
    while index < len(urls):
        print(urls[index].text)
        with open("D:\\urls.csv", "a", newline="") as urll:
            writer = csv.writer(urll)
            writer.writerow([urls[index].text])
            index += 1
        print("Calling Deeper Level")
        ScrapPage(urls[index].text)
        

urls = []

headers = {"Accept": "*/*", "User-Agent": "PostmanRuntime/7.24.0","Accept-Encoding":"gzip, deflate, br","Connection":"keep-alive"}
ScrapPage("https://sweatcoinguide.com/sitemap_index.xml")
print('done')

**Comment by shukrant25** [comment]
Thanks, Shreyar for the addition, Here's the one with proper indentation.

```
def ScrapPage(urlMain):
    response = get(urlMain,headers=headers)
    content = BeautifulSoup(response.content, "lxml")
    urls = content.find_all("loc")
    index = 0
    while index < len(urls):
        print(urls[index].text)
        with open("urlsnew.csv", "a", newline="") as urll:
            writer = csv.writer(urll)
            writer.writerow([urls[index].text])
            index += 1
        print("Calling Deeper Level")
        ScrapPage(urls[index].text)

urls = []

headers = {"Accept": "/", "User-Agent": "PostmanRuntime/7.24.0","Accept-Encoding":"gzip, deflate, br","Connection":"keep-alive"}
ScrapPage("https://sweatcoinguide.com/sitemap_index.xml")
print('done')
